{% set name = "s2downloader" %}
{% set version = "1.4.6" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/s2downloader-{{ version }}.tar.gz
  sha256: d715e4a1ea469deb3b3b00182ec3670b0fbcb7080b1f8874ddaa894c4a1326bc

build:
  entry_points:
    - s2downloader=s2downloader.s2downloader_cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pytest-runner
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - numpy >=2.0
    - affine
    - pyproj
    - geojson
    - geojson-pydantic
    - rasterio
    - geopandas >=1.0
    - shapely
    - pystac
    - geopy
    - pystac-client
    - pydantic

test:
  imports:
    - s2downloader
  commands:
    - pip check
    - s2downloader --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://git.gfz-potsdam.de/fernlab/products/s2downloader
  summary: Downloader for Sentinel-2 from aws.
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danschef
    - jo-kno
    - DaRa42
