{% set name = "s2downloader" %}
{% set version = "1.4.5" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/s2downloader-{{ version }}.tar.gz
  sha256: 98a2c64d2d8f84590d9bdf9f25be560799bb7499b8abce334db325e60ccd477d

build:
  entry_points:
    - s2downloader=s2downloader.s2downloader_cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pytest-runner
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - gdal
    - affine
    - pyproj
    - numpy
    - matplotlib-base
    - geojson
    - rasterio
    - geopy
    - pandas
    - geopandas >=0.11
    - shapely
    - rtree
    - python-dateutil
    - pystac
    - pystac-client
    - pydantic
    - geojson-pydantic

test:
  imports:
    - s2downloader
  commands:
    - pip check
    - s2downloader --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://git.gfz-potsdam.de/fernlab/products/data-portal/s2downloader
  summary: Downloader for Sentinel-2 from aws.
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danschef
    - romulogoncalves
    - DaRa42
