{% set name = "s2downloader" %}
{% set version = "1.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/s2downloader-{{ version }}.tar.gz
  sha256: e1142b4f4162bdc1b6a2f9e7858371340396bffae13d756c24bfcc0bf4684378

build:
  entry_points:
    - s2downloader=s2downloader.s2downloader_cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pytest-runner
    - pip
  run:
    - python >=3.7
    - gdal
    - affine
    - pyproj
    - numpy
    - matplotlib-base
    - geojson
    - rasterio
    - geopy
    - pandas
    - geopandas >=0.11
    - shapely
    - rtree
    - python-dateutil
    - pystac
    - pystac-client
    - pydantic
    - geojson-pydantic

test:
  imports:
    - s2downloader
  commands:
    - pip check
    - s2downloader --help
  requires:
    - pip

about:
  home: https://git.gfz-potsdam.de/fernlab/products/data-portal/s2downloader
  summary: Downloader for Sentinel-2 from aws.
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - romulogoncalves
    - DaRa42
